### ISSUE TITLE
Segfault whenever I try to eval/print any variable

### ISSUE THREAD

**Issue by saimonmoore** [smtlaissezfaire/ndb#2]
Using ndb master and node 0.1.97 under ubuntu hardy (as vm guest)

**Comment by saimonmoore** [comment]
Not much else to go on :(

**Comment by smtlaissezfaire** [comment]
Mind passing along the code in which it's doing so?

This probably isn't a bug in ndb - it's probably a bug either in v8 or node.

**Comment by saimonmoore** [comment]
debugging nodered (Added a debug statement here: http://bit.ly/aBfyZp) trying: p this.ip or e this.ip (or any variable really) result in the segfault...

**Comment by smtlaissezfaire** [comment]
I can't seem to get that far - I'm getting a ReferenceError when requiring 'request_dispatch':

http://gist.github.com/423857

What versions of node & ndb are you using?

**Comment by saimonmoore** [comment]
You'd need to add a debugger statement to the line I showed you and
then run the nodered server in bin:

bin/nodered.js

(Caviat: you also need redis running locally for it to work)

ndb: lastet master
node: 0.1.97

**Comment by smtlaissezfaire** [comment]
Have you tried it on node 0.1.96?

So far, the test suite isn't running for ndb with node 0.1.97.  I had chalked it up to a bug with jspec (which it still might be).

**Comment by saimonmoore** [comment]
Not yet but I will and will report back...thanks

**Comment by smtlaissezfaire** [comment]
Another idea is to use the new repl instead of print/eval.  For various technical reasons, the repl doesn't try to pretty-print the value, where print/eval does.

Anyway - don't segfaults usually print out [Segmentation Fault] at the end of the process (in bash?)?  I noticed the process closing without any extra status at the end, although haven't checked the return value.

**Comment by keturn** [comment]
just ran in to this.  repl also segfaults.  (node 0.2.2, ndb from git)

**Comment by smtlaissezfaire** [comment]
What code are you debugging?  What version of ndb (off of which branch)?

Mind sending me some output?

**Comment by keturn** [comment]
debugging this: http://github.com/keturn/lintnode/blob/master//app.js
using the master branch of ndb at commit 5a29822e

```
$ node --debug-brk app.js
debugger listening on port 5858
Segmentation fault

$ bin/ndb
welcome to the node debugger!
ndb> p 7
```

(that's from two different windows; the node segfault occurs immediately after issuing the "p" command to ndb.)

**Comment by smtlaissezfaire** [comment]
What version of node?

**Comment by keturn** [comment]
node 0.2.2 installed from http://ppa.launchpad.net/jerome-etienne/neoip/ubuntu/ on x86_64

**Comment by smtlaissezfaire** [comment]
Closing it out - this project is no longer being supported.  Use the mainline debugger.
