### ISSUE TITLE
Error fetching ndb

### ISSUE THREAD

**Issue by diogobaeder** [smtlaissezfaire/ndb#4]
Hi,

I'm using ndb as a submodule, and I'm having problems trying to recursively fetch it from github, because the ndb's submodule "spec/espionage" is failing to be cloned. Could you please take a look?

Thanks!

**Comment by smtlaissezfaire** [comment]
Ok - that's now updated in the dev branch.  Note that you should also delete any submodule entires in .git/config before you run submodule update --init again.

Out of curiosity, how/why are you using it as a submodule?

**Comment by diogobaeder** [comment]
Thanks for the correction.

I'm using as a submodule because I thought it would be easier for other contributors of my project to deal with debuggind, but after a second thought it's more logical to have such a tool as an external dependency. I'll not put it as a submodule again, but use it as a stand-alone aplication. :-)

**Comment by smtlaissezfaire** [comment]
Neat.  Let me know when you've released it.

Also, AFAIK, all of those dependencies are _only_ for running specs.
